<?php

namespace Container7oOnQQQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T4iRIjmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t4iRIjm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t4iRIjm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'addUser' => ['privates', 'App\\Service\\AddUser', 'getAddUserService', true],
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRep' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'addUser' => 'App\\Service\\AddUser',
            'encoder' => '?',
            'manager' => '?',
            'userRep' => 'App\\Repository\\UserRepository',
        ]);
    }
}
