<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxnuiPU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxnuiPU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxnuiPU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxnuiPU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxnuiPU\App_KernelDevDebugContainer([
    'container.build_hash' => 'BxnuiPU',
    'container.build_id' => 'a8c90de4',
    'container.build_time' => 1609542812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxnuiPU');
